server:
  port: 8088
  session-timeout: 1800
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://139.199.117.78:3306/uc_main_demo?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 8sjdlld@s09j__
  jpa:
    show-sql: true
  redis:
    shiro:
      host: 139.199.117.78
      port: 6379
      password: @sijkkks08988kk
      # 连接超时时间（毫秒）
      timeout: 10000
 
logging:
  level:
    cn.daimalaoge : debug