server:
  port: 8088
  session-timeout: 1800
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/uc_main_demo?autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
  jpa:
    show-sql: true

 
logging:
  level:
    cn.daimalaoge : debug